#!/usr/bin/env python3
"""The map of the film's sound: every event of the picture and the sound that answers it (needs numpy + scipy: it reads the class table of tools/audio/sfx.py).

    python3 scripts/qa/sound-map.py [--md qa/SOUND-MAP.md]

Reads audio/picture-events.json (what the picture does) and audio/cues.json (what plays, with each cue's `event` / `eventT` pointing back at the picture event it answers)
and writes one table per scene: the picture event, when it happens, the sound that answers it, its loudness class and its final level (its own gain: class, per-cue gain,
the balance audit's trim). An event with no sound says why. Nothing in the film is missing from this table: scripts/qa/av-coverage.py fails the build of the audit if it is.
"""
import argparse, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "audio"))
sys.dont_write_bytecode = True
import sfx  # noqa: E402

SCENES = [("hook", "Hook (0 – 4 s)"), ("lockup", "Lock-up (3.6 – 6.2 s)"), ("ipad", "iPad flow (5.4 – 26.6 s)"), ("phone", "iPhone e-mail (25.6 – 34.2 s)"),
          ("store", "Manager & Stats (33.6 – 44.2 s)"), ("consult", "Consultants (43.6 – 54.2 s)"), ("system", "System (53.6 – 57.9 s)"), ("human", "Human close (57.5 – 61.5 s)"),
          ("end", "End card (61 – 64.5 s)"), ("caption", "Captions"), ("transition", "Scene transitions")]
CLASS_NAME = {"H": "highlight", "A": "action", "W": "movement", "T": "texture", "t": "whisper"}


def times(ts, limit=6):
    ts = sorted(ts)
    if len(ts) <= limit:
        return ", ".join(f"{t:.2f}" for t in ts)
    return f"{ts[0]:.2f} … {ts[-1]:.2f} ({len(ts)}×)"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--md", default=os.path.join(ROOT, "qa", "SOUND-MAP.md"))
    ap.add_argument("--events", default=os.path.join(ROOT, "audio", "picture-events.json"))
    ap.add_argument("--cues", default=os.path.join(ROOT, "audio", "cues.json"))
    a = ap.parse_args()
    events = json.load(open(a.events))["events"]
    cues = json.load(open(a.cues))["sfx"]
    by_event = {}
    for c in cues:
        if "event" in c:
            by_event[(c["event"], round(float(c["eventT"]), 3))] = c

    out = ["# The sound of every event of the picture", "",
           f"{len(events)} things happen in the picture that deserve a sound; **{sum(1 for e in events if not e.get('silent'))}** have one of their own, the other {sum(1 for e in events if e.get('silent'))} are covered by the sound next to them and say why. "
           "Each row below groups the events of one kind; *class* is the loudness class the sound is levelled to (see `qa/SOUND-AUDIT.md`):",
           "**signature** the film's few big moments · **highlight** an arrival or a confirmation · **action** something the viewer does or reads · **movement** air that follows the picture · "
           "**texture** keystrokes, ticks, small pops · **whisper** the quietest touches.", "",
           "Generated by `scripts/qa/sound-map.py` from `audio/picture-events.json` and `audio/cues.json`.", ""]
    for scene, title in SCENES:
        evs = [e for e in events if e["scene"] == scene]
        if not evs:
            continue
        out += [f"## {title}", "", "| picture event | when (s) | sound | class | level (dB re class) |", "|---|---|---|---|---|"]
        kinds = []
        for e in evs:
            if e["kind"] not in [k for k, _ in kinds]:
                kinds.append((e["kind"], [x for x in evs if x["kind"] == e["kind"]]))
        for kind, group in kinds:
            label = group[0]["label"] if len(group) == 1 else _kind_label(kind, group)
            ts = [g["t"] for g in group]
            sounds, classes, gains = [], set(), []
            reason = None
            for g in group:
                c = by_event.get((g["kind"], round(float(g["t"]), 3)))
                if c is None:
                    reason = g.get("silent") or "no cue"
                    continue
                sounds.append(c["type"])
                cl = sfx.CLASS_OF.get(c["type"])
                classes.add(CLASS_NAME[cl[0]] if cl else ("signature" if c["type"] in S_TYPES else "hand-set"))
                gains.append(float(c.get("gain_db", 0.0)))
            if not sounds:
                out.append(f"| {label} | {times(ts)} | — | — | *{reason}* |")
                continue
            uniq = sorted(set(sounds), key=sounds.index)
            snd = " + ".join(f"`{s}`" for s in uniq)
            lv = f"{min(gains):+.1f}" if min(gains) == max(gains) else f"{min(gains):+.1f} … {max(gains):+.1f}"
            note = f" *(+ {len(group) - len(sounds)} silent: {reason})*" if reason and len(sounds) < len(group) else ""
            out.append(f"| {label} | {times(ts)} | {snd}{note} | {' / '.join(sorted(classes))} | {lv} |")
        out.append("")
    open(a.md, "w").write("\n".join(out))
    print(f"wrote {a.md}")


KIND_NAMES = {
    "tile-pop": "gadget cards pop in", "tile-pop-ghost": "out-of-focus extra cards", "word": "headline words land", "twinkles": "sparkles twinkle", "letter": "wordmark letters pop in",
    "select": "language highlight hops", "field-focus": "a form field takes focus", "key": "keystrokes", "tap": "finger taps", "page": "a screen fades / pushes in",
    "callout": "a label or ring pops in", "card-in": "question cards enter", "swipe": "swipes", "dot": "progress dots light up", "count": "scan counter steps",
    "consent-tick": "consent ticks", "chip": "chips pop in", "lead-fly": "a lead flies to the CRM", "lead-land": "a lead lands in the CRM", "node": "diagram nodes pop in",
    "line": "lines draw themselves", "packet": "data starts to flow", "tile": "dashboard tiles rise", "lock": "locks (padlock, RLS, MFA)", "caption": "captions open",
    "caption-line": "caption underlines draw", "transition": "scene transitions", "sample": "the \"Sample data\" chip appears", "scroll": "a page scrolls", "shimmer": "a sheen sweeps the logo mark",
    "shine": "a light sweep crosses a card", "tagline": "a line of text rises", "zoom": "the camera zooms", "lean": "the camera leans in", "pulse": "success rings pulse", "confetti": "confetti bursts",
    "page-push": "a page pushes in", "photo-cut": "cut to a photograph", "photo-cross": "photographs cross",
}
S_TYPES = {"logo-hit", "counter-hit", "handshake", "motif", "motif-q", "lock-on"}


def _kind_label(kind, group):
    return f"{KIND_NAMES.get(kind, kind)} ×{len(group)}"


if __name__ == "__main__":
    main()
